config/routes.rb
Rails.application.routes.draw do
  resources :datapoints

  resources :publishers

  resources :recipes

  resources :diets

  resources :categories

  resources :eases

  resources :occasions

  resources :cusines

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/datapoint.rb
class Datapoint < ActiveRecord::Base
  belongs_to :publisher
end

app/controllers/datapoints_controller.rb
class DatapointsController < ApplicationController
  before_action :set_datapoint, only: [:show, :edit, :update, :destroy]

  # GET /datapoints
  # GET /datapoints.json
  def index
    @datapoints = Datapoint.all
  end

  # GET /datapoints/1
  # GET /datapoints/1.json
  def show
  end

  # GET /datapoints/new
  def new
    @datapoint = Datapoint.new
  end

  # GET /datapoints/1/edit
  def edit
  end

  # POST /datapoints
  # POST /datapoints.json
  def create
    @datapoint = Datapoint.new(datapoint_params)

    respond_to do |format|
      if @datapoint.save
        format.html { redirect_to @datapoint, notice: 'Datapoint was successfully created.' }
        format.json { render :show, status: :created, location: @datapoint }
      else
        format.html { render :new }
        format.json { render json: @datapoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /datapoints/1
  # PATCH/PUT /datapoints/1.json
  def update
    respond_to do |format|
      if @datapoint.update(datapoint_params)
        format.html { redirect_to @datapoint, notice: 'Datapoint was successfully updated.' }
        format.json { render :show, status: :ok, location: @datapoint }
      else
        format.html { render :edit }
        format.json { render json: @datapoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /datapoints/1
  # DELETE /datapoints/1.json
  def destroy
    @datapoint.destroy
    respond_to do |format|
      format.html { redirect_to datapoints_url, notice: 'Datapoint was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_datapoint
      @datapoint = Datapoint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def datapoint_params
      params.require(:datapoint).permit(:publisher_id, :titlexpath, :titlecss, :titleregex, :descriptionxpath, :descriptioncss, :descriptionregex, :imagexpath, :imagecss, :imageregex, :imagecreditxpath, :imagecreditcss, :imagecreditregex, :yeildxpath, :yeildcss, :yeildregex, :prepxpath, :prepcss, :prepregex, :cookxpath, :cookcss, :cookregex, :totalxpath, :totalcss, :totalregex, :ingredientsxpath, :ingredientscss, :ingredientsregex, :dietxpath, :dietcss, :dietregex, :coursexpath, :coursecss, :courseregex, :easexpath, :easecss, :easeregex, :categoriesxpath, :categoriescss, :categoriesregex, :tagsxpath, :tagscss, :tagsregex, :ratingxpath, :ratingcss, :ratingregex, :commentnumxpath, :commentnumcss, :commentnumregex, :facebookxpath, :facebookcss, :facebookregex, :twitterxpath, :twittercss, :twitterregex, :pinxpath, :pincss, :pinregex, :stumblexpath, :stumblecss, :stumbleregex, :gxpath, :gcss, :gregex, :publisherdatexpath, :publisherdatecss, :publisherdateregex, :authorxpath, :authorcss, :authorregex, :sources)
    end
end

app/helpers/datapoints_helper.rb
module DatapointsHelper
end

app/views/datapoints/edit.html.erb
<%- model_class = Datapoint -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Datapoint %></h1>
</div>
<%= render :partial => 'form' %>

app/views/datapoints/index.html.erb
<%- model_class = Datapoint -%>
<div class="page-header">
  <h1><%=t '.title', :default => Datapoint %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:titlexpath) %></th>
      <th><%= model_class.human_attribute_name(:titlecss) %></th>
      <th><%= model_class.human_attribute_name(:titleregex) %></th>
      <th><%= model_class.human_attribute_name(:descriptionxpath) %></th>
      <th><%= model_class.human_attribute_name(:descriptioncss) %></th>
      <th><%= model_class.human_attribute_name(:descriptionregex) %></th>
      <th><%= model_class.human_attribute_name(:imagexpath) %></th>
      <th><%= model_class.human_attribute_name(:imagecss) %></th>
      <th><%= model_class.human_attribute_name(:imageregex) %></th>
      <th><%= model_class.human_attribute_name(:imagecreditxpath) %></th>
      <th><%= model_class.human_attribute_name(:imagecreditcss) %></th>
      <th><%= model_class.human_attribute_name(:imagecreditregex) %></th>
      <th><%= model_class.human_attribute_name(:yeildxpath) %></th>
      <th><%= model_class.human_attribute_name(:yeildcss) %></th>
      <th><%= model_class.human_attribute_name(:yeildregex) %></th>
      <th><%= model_class.human_attribute_name(:prepxpath) %></th>
      <th><%= model_class.human_attribute_name(:prepcss) %></th>
      <th><%= model_class.human_attribute_name(:prepregex) %></th>
      <th><%= model_class.human_attribute_name(:cookxpath) %></th>
      <th><%= model_class.human_attribute_name(:cookcss) %></th>
      <th><%= model_class.human_attribute_name(:cookregex) %></th>
      <th><%= model_class.human_attribute_name(:totalxpath) %></th>
      <th><%= model_class.human_attribute_name(:totalcss) %></th>
      <th><%= model_class.human_attribute_name(:totalregex) %></th>
      <th><%= model_class.human_attribute_name(:ingredientsxpath) %></th>
      <th><%= model_class.human_attribute_name(:ingredientscss) %></th>
      <th><%= model_class.human_attribute_name(:ingredientsregex) %></th>
      <th><%= model_class.human_attribute_name(:dietxpath) %></th>
      <th><%= model_class.human_attribute_name(:dietcss) %></th>
      <th><%= model_class.human_attribute_name(:dietregex) %></th>
      <th><%= model_class.human_attribute_name(:coursexpath) %></th>
      <th><%= model_class.human_attribute_name(:coursecss) %></th>
      <th><%= model_class.human_attribute_name(:courseregex) %></th>
      <th><%= model_class.human_attribute_name(:easexpath) %></th>
      <th><%= model_class.human_attribute_name(:easecss) %></th>
      <th><%= model_class.human_attribute_name(:easeregex) %></th>
      <th><%= model_class.human_attribute_name(:categoriesxpath) %></th>
      <th><%= model_class.human_attribute_name(:categoriescss) %></th>
      <th><%= model_class.human_attribute_name(:categoriesregex) %></th>
      <th><%= model_class.human_attribute_name(:tagsxpath) %></th>
      <th><%= model_class.human_attribute_name(:tagscss) %></th>
      <th><%= model_class.human_attribute_name(:tagsregex) %></th>
      <th><%= model_class.human_attribute_name(:ratingxpath) %></th>
      <th><%= model_class.human_attribute_name(:ratingcss) %></th>
      <th><%= model_class.human_attribute_name(:ratingregex) %></th>
      <th><%= model_class.human_attribute_name(:commentnumxpath) %></th>
      <th><%= model_class.human_attribute_name(:commentnumcss) %></th>
      <th><%= model_class.human_attribute_name(:commentnumregex) %></th>
      <th><%= model_class.human_attribute_name(:facebookxpath) %></th>
      <th><%= model_class.human_attribute_name(:facebookcss) %></th>
      <th><%= model_class.human_attribute_name(:facebookregex) %></th>
      <th><%= model_class.human_attribute_name(:twitterxpath) %></th>
      <th><%= model_class.human_attribute_name(:twittercss) %></th>
      <th><%= model_class.human_attribute_name(:twitterregex) %></th>
      <th><%= model_class.human_attribute_name(:pinxpath) %></th>
      <th><%= model_class.human_attribute_name(:pincss) %></th>
      <th><%= model_class.human_attribute_name(:pinregex) %></th>
      <th><%= model_class.human_attribute_name(:stumblexpath) %></th>
      <th><%= model_class.human_attribute_name(:stumblecss) %></th>
      <th><%= model_class.human_attribute_name(:stumbleregex) %></th>
      <th><%= model_class.human_attribute_name(:gxpath) %></th>
      <th><%= model_class.human_attribute_name(:gcss) %></th>
      <th><%= model_class.human_attribute_name(:gregex) %></th>
      <th><%= model_class.human_attribute_name(:publisherdatexpath) %></th>
      <th><%= model_class.human_attribute_name(:publisherdatecss) %></th>
      <th><%= model_class.human_attribute_name(:publisherdateregex) %></th>
      <th><%= model_class.human_attribute_name(:authorxpath) %></th>
      <th><%= model_class.human_attribute_name(:authorcss) %></th>
      <th><%= model_class.human_attribute_name(:authorregex) %></th>
      <th><%= model_class.human_attribute_name(:sources) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @datapoints.each do |datapoint| %>
      <tr>
        <td><%= datapoint.id %></td>
        <td><%= datapoint.titlexpath %></td>
        <td><%= datapoint.titlecss %></td>
        <td><%= datapoint.titleregex %></td>
        <td><%= datapoint.descriptionxpath %></td>
        <td><%= datapoint.descriptioncss %></td>
        <td><%= datapoint.descriptionregex %></td>
        <td><%= datapoint.imagexpath %></td>
        <td><%= datapoint.imagecss %></td>
        <td><%= datapoint.imageregex %></td>
        <td><%= datapoint.imagecreditxpath %></td>
        <td><%= datapoint.imagecreditcss %></td>
        <td><%= datapoint.imagecreditregex %></td>
        <td><%= datapoint.yeildxpath %></td>
        <td><%= datapoint.yeildcss %></td>
        <td><%= datapoint.yeildregex %></td>
        <td><%= datapoint.prepxpath %></td>
        <td><%= datapoint.prepcss %></td>
        <td><%= datapoint.prepregex %></td>
        <td><%= datapoint.cookxpath %></td>
        <td><%= datapoint.cookcss %></td>
        <td><%= datapoint.cookregex %></td>
        <td><%= datapoint.totalxpath %></td>
        <td><%= datapoint.totalcss %></td>
        <td><%= datapoint.totalregex %></td>
        <td><%= datapoint.ingredientsxpath %></td>
        <td><%= datapoint.ingredientscss %></td>
        <td><%= datapoint.ingredientsregex %></td>
        <td><%= datapoint.dietxpath %></td>
        <td><%= datapoint.dietcss %></td>
        <td><%= datapoint.dietregex %></td>
        <td><%= datapoint.coursexpath %></td>
        <td><%= datapoint.coursecss %></td>
        <td><%= datapoint.courseregex %></td>
        <td><%= datapoint.easexpath %></td>
        <td><%= datapoint.easecss %></td>
        <td><%= datapoint.easeregex %></td>
        <td><%= datapoint.categoriesxpath %></td>
        <td><%= datapoint.categoriescss %></td>
        <td><%= datapoint.categoriesregex %></td>
        <td><%= datapoint.tagsxpath %></td>
        <td><%= datapoint.tagscss %></td>
        <td><%= datapoint.tagsregex %></td>
        <td><%= datapoint.ratingxpath %></td>
        <td><%= datapoint.ratingcss %></td>
        <td><%= datapoint.ratingregex %></td>
        <td><%= datapoint.commentnumxpath %></td>
        <td><%= datapoint.commentnumcss %></td>
        <td><%= datapoint.commentnumregex %></td>
        <td><%= datapoint.facebookxpath %></td>
        <td><%= datapoint.facebookcss %></td>
        <td><%= datapoint.facebookregex %></td>
        <td><%= datapoint.twitterxpath %></td>
        <td><%= datapoint.twittercss %></td>
        <td><%= datapoint.twitterregex %></td>
        <td><%= datapoint.pinxpath %></td>
        <td><%= datapoint.pincss %></td>
        <td><%= datapoint.pinregex %></td>
        <td><%= datapoint.stumblexpath %></td>
        <td><%= datapoint.stumblecss %></td>
        <td><%= datapoint.stumbleregex %></td>
        <td><%= datapoint.gxpath %></td>
        <td><%= datapoint.gcss %></td>
        <td><%= datapoint.gregex %></td>
        <td><%= datapoint.publisherdatexpath %></td>
        <td><%= datapoint.publisherdatecss %></td>
        <td><%= datapoint.publisherdateregex %></td>
        <td><%= datapoint.authorxpath %></td>
        <td><%= datapoint.authorcss %></td>
        <td><%= datapoint.authorregex %></td>
        <td><%= datapoint.sources %></td>
        <td><%=l datapoint.created_at, format: :long %></td>
        <td>
          <%= link_to datapoint_path(datapoint), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to datapoint_path(datapoint), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_datapoint_path,
            :class => 'btn btn-primary' %>

app/views/datapoints/new.html.erb
<%- model_class = Datapoint -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Datapoint %></h1>
</div>
<%= render :partial => 'form' %>

app/views/datapoints/show.html.erb
<%- model_class = Datapoint -%>
<div class="page-header">
  <h1><%=t '.title', :default => Datapoint %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:titlexpath) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.titlexpath %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:titlecss) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.titlecss %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:titleregex) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.titleregex %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:descriptionxpath) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.descriptionxpath %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:descriptioncss) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.descriptioncss %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:descriptionregex) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.descriptionregex %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:imagexpath) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.imagexpath %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:imagecss) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.imagecss %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:imageregex) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.imageregex %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:imagecreditxpath) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.imagecreditxpath %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:imagecreditcss) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.imagecreditcss %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:imagecreditregex) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.imagecreditregex %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:yeildxpath) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.yeildxpath %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:yeildcss) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.yeildcss %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:yeildregex) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.yeildregex %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:prepxpath) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.prepxpath %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:prepcss) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.prepcss %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:prepregex) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.prepregex %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:cookxpath) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.cookxpath %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:cookcss) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.cookcss %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:cookregex) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.cookregex %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:totalxpath) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.totalxpath %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:totalcss) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.totalcss %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:totalregex) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.totalregex %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:ingredientsxpath) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.ingredientsxpath %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:ingredientscss) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.ingredientscss %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:ingredientsregex) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.ingredientsregex %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:dietxpath) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.dietxpath %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:dietcss) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.dietcss %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:dietregex) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.dietregex %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:coursexpath) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.coursexpath %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:coursecss) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.coursecss %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:courseregex) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.courseregex %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:easexpath) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.easexpath %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:easecss) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.easecss %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:easeregex) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.easeregex %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:categoriesxpath) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.categoriesxpath %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:categoriescss) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.categoriescss %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:categoriesregex) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.categoriesregex %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:tagsxpath) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.tagsxpath %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:tagscss) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.tagscss %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:tagsregex) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.tagsregex %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:ratingxpath) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.ratingxpath %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:ratingcss) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.ratingcss %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:ratingregex) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.ratingregex %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:commentnumxpath) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.commentnumxpath %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:commentnumcss) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.commentnumcss %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:commentnumregex) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.commentnumregex %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:facebookxpath) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.facebookxpath %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:facebookcss) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.facebookcss %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:facebookregex) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.facebookregex %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:twitterxpath) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.twitterxpath %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:twittercss) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.twittercss %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:twitterregex) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.twitterregex %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:pinxpath) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.pinxpath %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:pincss) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.pincss %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:pinregex) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.pinregex %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:stumblexpath) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.stumblexpath %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:stumblecss) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.stumblecss %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:stumbleregex) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.stumbleregex %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:gxpath) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.gxpath %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:gcss) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.gcss %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:gregex) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.gregex %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:publisherdatexpath) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.publisherdatexpath %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:publisherdatecss) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.publisherdatecss %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:publisherdateregex) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.publisherdateregex %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:authorxpath) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.authorxpath %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:authorcss) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.authorcss %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:authorregex) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.authorregex %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:sources) %></dt>
      <dd><pre class="prettyprint"><%= @datapoint.sources %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              datapoints_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_datapoint_path(@datapoint), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              datapoint_path(@datapoint),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>